# -*- coding: utf-8 -*-
"""Creación de dimensiones_HelenAlcivar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJmMtl_atS9QSqQ6flOoRWntEGjAc7x2
"""

import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey
from sqlalchemy import inspect

engine = create_engine('sqlite:///chinook.db')
engine

#datawarehouse
engine2 = create_engine('sqlite:///DW_Sales_MusicHA.db')
engine2

metadata = MetaData()
metadata.create_all(engine)
inspector = inspect(engine)

metadata2 = MetaData()
metadata2.create_all(engine2)
inspector2 = inspect(engine2)
inspector2.get_columns('dim_artists')

frame1 = pd.read_sql_query("""SELECT Title from albums; """, 
    con=engine.connect())

print (frame1)

frame2 = pd.read_sql_query("""SELECT Name from artists; """, 
    con=engine.connect())

print (frame2)

frame3 = pd.read_sql_query("""SELECT FirstName, LastName, Company, Address, City, State, Country, PostalCode, Phone, Fax, Email from customers; """, 
    con=engine.connect())

print (frame3)

frame4 = pd.read_sql_query("""SELECT Name from genres; """, 
    con=engine.connect())

print (frame4)

frame5 = pd.read_sql_query("""SELECT UnitPrice, Quantity from invoice_items; """, 
    con=engine.connect())

print (frame5)

frame6 = pd.read_sql_query("""SELECT BillingAddress,BillingCity, BillingCountry from invoices; """, 
    con=engine.connect())

print (frame6)

frame7= pd.read_sql_query("""SELECT Name from playlists; """, 
    con=engine.connect())

print (frame7)

frame8= pd.read_sql_query("""SELECT LastName,FirstName,Title,BirthDate ,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email  from employees; """, 
    con=engine.connect())

print (frame8)

"""TRANSFORMAR """

frame1.fillna("N/A", inplace = True)

frame2.fillna("N/A", inplace = True)

frame3.fillna("N/A", inplace = True)

frame4.fillna("N/A", inplace = True)

frame5.fillna("N/A", inplace = True)

frame6.fillna("N/A", inplace = True)

frame7.fillna("N/A", inplace = True)

frame8.fillna("N/A", inplace = True)

"""Cargar"""

frame1.to_sql(name='dim_albums', con=engine2, if_exists='append',index=False)

frame2.to_sql(name='dim_artist', con=engine2, if_exists='append',index=False)

frame3.to_sql(name='dim_customers', con=engine2, if_exists='append',index=False)

frame4.to_sql(name='dim_genres', con=engine2, if_exists='append',index=False)

frame5.to_sql(name='dim_invoice_items', con=engine2, if_exists='append',index=False)

frame6.to_sql(name='dim_invoices', con=engine2, if_exists='append',index=False)

frame7.to_sql(name='dim_playlist', con=engine2, if_exists='append',index=False)

frame8.to_sql(name='dim_employees', con=engine2, if_exists='append',index=False)

frame0 = pd.read_sql_query("""SELECT * from dim_artist; """, 
    con=engine2.connect())

print (frame0)